### ISSUE TITLE
dryer

### ISSUE THREAD

**Issue by gosip** [freeuni-sdp/iot-sim-bath#1]
[wiki](https://github.com/freeuni-sdp/iot-main/wiki/Simulator)-ში input-მოწყობილობებს შორის dryer გვიწერია, და ეგ რა არის? მაგას წერს საერთოდ ვინმე? @gkiko

**Comment by gkiko** [comment]
ეგ უბრალოდ მაგალითია სიმულატორის input-ის. როდესაც საშრობი ჩართულია
ტენიანობა იმატებს. არავინ წერს მაგ სერვისს
