### ISSUE TITLE
bath simulator -> humidity sensor shadow <- climate

### ISSUE THREAD

**Issue by gosip** [freeuni-sdp/iot-sim-bath#2]
@Rshalika @Davit-Qobuladze
თანახმა ხართ ასეთ სქემაზე?

სიმულატორი http post-ის საშუალებით უგზავნის humidity sensor shadow-ს გაზომვის მონაცემებს (ამ ნაწილს მე და გიო ვწერთ სიმულატორში), და climate თავისი საჭიროების მიხედვით poll-ავს ამ shadow-ს [ამ API](http://docs.iotbathhumiditysensor.apiary.io/)-ს მიხედვით.

**Comment by Rshalika** [comment]
დაპოლვაში გეთანხმებით 100% სენსორის ეგ ნაწილი დაწერეთ კიბატონო. მერე light ც დაწერს და თუ იქნება რამე დასამატებელი დავწერთ ჩვენც. bath-climate სულ პოლავს ორივე სერვისს

**Comment by gkink** [comment]
@Rshalika @Davit-Qobuladze
API-ში რამე ცვლილება ხო არ გინდათ?

**Comment by Rshalika** [comment]
შედოუში არ ვიცი room ის id საჭიროა თუ არა 
ერთხელ კიკოლამ მითხრა სახლს ერთი აბაზანა აქვსო. default ად "1" გამოვიყენოთ ჯერ

**Comment by gkink** [comment]
@gkiko
გიო ჩავთვალოთ რო ერთი აბაზანა აქვს სახლს?

**Comment by Rshalika** [comment]
"ბევრი ოთახი არ გვაქვს"

კიკოლა

**Comment by gkiko** [comment]
ტენიანობის მომქტებაზე სწრაფი რეაგირება გვინდა. ხშირად დაპოლეთ, ან შედოუმ
დაუფორვარდოს მონაცემები რეგულქტორს.

**Comment by gosip** [comment]
@gkiko ტენიანობის სენსორის API-ს ოთახის id მოვაშოროთ?

**Comment by Rshalika** [comment]
ხშირად დავპოლავთ
