### ISSUE TITLE
ადმინისტრაციული პრივილეგიები

### ISSUE THREAD

**Issue by wrinkl3** [freeuni-sdp/iot-sim-bath#3]
@gkiko ტრევისზე და ჰეროკუზე ვერ ვწვევთ იმიტომ, რომ შესაბამისი პრივილეგიები რეპოზიტორიაზე არ გვაქვს.

**Comment by gkiko** [comment]
მე დავამატე ტრეივისზე. კონფიგურაციის ფაილი რომ ჩააგდო იმუშავებს

**Comment by wrinkl3** [comment]
@gkiko ჰეროკუს რა ვუყოთ?

**Comment by gkiko** [comment]
შექმნილი გაქვთ უკვე ჰეროკუები?

**Comment by wrinkl3** [comment]
ჩვენ-ჩვენი პროექტების კი. ამ სპრინტში სიმულატორის ჰეროკუზე გაშვება არ გვევალება?

**Comment by gkiko** [comment]
კი გევალებათ. ერთერთმა გაუშვით

2016-06-25 18:27 GMT+04:00 wrinkl3 notifications@github.com:

**Comment by wrinkl3** [comment]
პრივილეგიები არ გვაქვს.

**Comment by gkiko** [comment]
@nikachx და @Megatvini თავიანთ ჰეროკუებს მიაბეს. ყველას ერთნაირი პრივილეგიები გაქვთ. მათ მიმართე ინსტრუქციებისთვის
